name: Code checks

on:
    push:
    pull_request:
jobs:
    Lint:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v4.1.1

            -   name: Set up Python 3.13
                uses: actions/setup-python@v5.0.0
                with:
                    python-version: "3.13"

            -   name: Install dependencies
                run: |
                    python -m pip install --upgrade pip
                    python -m pip install cpplint

            -   name: Analyze with cpplint
                run: |
                    python -m cpplint $(git ls-files '*.h') $(git ls-files '*.cpp')
